# @format

name: Keep Pages Alive

on:
   schedule:
      - cron: "0 0 */5 * *"
   workflow_dispatch: {}

jobs:
   ping-supabase:
      runs-on: ubuntu-latest
      name: Ping Supabase API
      steps:
         - name: Validate Supabase Secrets
           run: |
              if [ -z "${SUPABASE_URL}" ] || [ -z "${SUPABASE_ANON_KEY}" ]; then
                echo "Error: SUPABASE_URL and/or SUPABASE_ANON_KEY secrets are not set."
                exit 1
              fi
              echo "Pinging Supabase API at $SUPABASE_URL"
           env:
              SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
              SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

         - name: Ping Supabase Database
           run: |
              curl --fail --silent --show-error --location "$SUPABASE_URL/rest/v1/base_words?limit=1" \
                -H "apikey: $SUPABASE_ANON_KEY" \
                -H "Authorization: Bearer $SUPABASE_ANON_KEY" > /dev/null
           env:
              SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
              SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
